import { normalizeVideoUrl } from '@/lib/video-embeds';

const livestream = normalizeVideoUrl('https://www.youtube.com/live/Dn1fsQ9gmNM?si=ybuZr9VBW2lqx_Jf');
const storyVideo = normalizeVideoUrl('https://vimeo.com/1178997927');

export const defaultEvent = {
  id: 'demo-event',
  owner_id: null,
  event_type: 'wedding',
  slug: 'surya-sowji',
  title: "Raja Surya & Bala Sowjanya's Wedding",
  hosts_display_name: 'Raja Surya & Bala Sowjanya',
  headline: 'Live with Family & Friends',
  description:
    'Welcome to the wedding celebration of Raja Surya and Bala Sowjanya. Watch the live stream, revisit pre-wedding moments, and share the page easily with family and friends.',
  event_datetime_utc: '2026-04-01T15:19:00.000Z',
  event_timezone: 'Asia/Kolkata',
  venue_name: 'Tanuku Wedding Celebration',
  venue_address: 'Tanuku, Andhra Pradesh, India',
  maps_url: 'https://maps.app.goo.gl/r4ZCnPRcyzhFv6pt5?g_st=iw',
  theme_key: 'rose-gold',
  status: 'published',
  sections: {
    hero_enabled: true,
    livestream_enabled: true,
    story_video_enabled: true,
    gallery_enabled: true,
    location_enabled: true,
    guestbook_enabled: true,
  },
  media_assets: [
    {
      id: 'hero-1',
      event_id: 'demo-event',
      kind: 'hero',
      source_type: 'external_url',
      storage_path: null,
      external_url: 'https://i.ibb.co/V0WvM7Hv/A7408826.jpg',
      public_url: 'https://i.ibb.co/V0WvM7Hv/A7408826.jpg',
      caption: 'Pre-wedding moment',
      alt_text: 'Couple portrait before the wedding',
      sort_order: 0,
      width: null,
      height: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'gallery-1',
      event_id: 'demo-event',
      kind: 'gallery',
      source_type: 'external_url',
      storage_path: null,
      external_url: 'https://i.ibb.co/V0WvM7Hv/A7408826.jpg',
      public_url: 'https://i.ibb.co/V0WvM7Hv/A7408826.jpg',
      caption: 'Pre-Wedding Moment',
      alt_text: 'Pre wedding portrait outdoors',
      sort_order: 0,
      width: null,
      height: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'gallery-2',
      event_id: 'demo-event',
      kind: 'gallery',
      source_type: 'external_url',
      storage_path: null,
      external_url: 'https://i.ibb.co/YTZ4pwCD/A7408835-copy.jpg',
      public_url: 'https://i.ibb.co/YTZ4pwCD/A7408835-copy.jpg',
      caption: 'Together at Home',
      alt_text: 'Candid portrait of the couple',
      sort_order: 1,
      width: null,
      height: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'gallery-3',
      event_id: 'demo-event',
      kind: 'gallery',
      source_type: 'external_url',
      storage_path: null,
      external_url: 'https://i.ibb.co/Kpy2px7n/A7409011.jpg',
      public_url: 'https://i.ibb.co/Kpy2px7n/A7409011.jpg',
      caption: 'Elegant Couple Portrait',
      alt_text: 'Formal couple portrait',
      sort_order: 2,
      width: null,
      height: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'gallery-4',
      event_id: 'demo-event',
      kind: 'gallery',
      source_type: 'external_url',
      storage_path: null,
      external_url: 'https://i.ibb.co/tTz6cvnR/A7409069.jpg',
      public_url: 'https://i.ibb.co/tTz6cvnR/A7409069.jpg',
      caption: 'Classic Piano Shot',
      alt_text: 'Piano wedding portrait',
      sort_order: 3,
      width: null,
      height: null,
      created_at: new Date().toISOString(),
    },
  ],
  video_embeds: [
    {
      id: 'video-live',
      event_id: 'demo-event',
      section_key: 'livestream',
      provider: livestream.provider,
      url: 'https://www.youtube.com/live/Dn1fsQ9gmNM?si=ybuZr9VBW2lqx_Jf',
      embed_url: livestream.embedUrl,
      title: 'Wedding livestream',
      description: 'Join us live as we celebrate the wedding from anywhere in the world.',
      thumbnail_url: livestream.thumbnailUrl,
      sort_order: 0,
    },
    {
      id: 'video-story',
      event_id: 'demo-event',
      section_key: 'pre_wedding',
      provider: storyVideo.provider,
      url: 'https://vimeo.com/1178997927',
      embed_url: storyVideo.embedUrl,
      title: 'Our Pre-Wedding Journey',
      description:
        'A glimpse into our beautiful moments together before the big day. We are so incredibly excited to share our story and this new chapter with all of you.',
      thumbnail_url: storyVideo.thumbnailUrl,
      sort_order: 0,
    },
  ],
  guestbook_entries: [
    {
      id: 'wish-1',
      event_id: 'demo-event',
      guest_name: 'Ananya',
      message: 'Wishing you both a beautiful life filled with joy, calm, and laughter.',
      created_at: new Date().toISOString(),
      status: 'approved',
    },
    {
      id: 'wish-2',
      event_id: 'demo-event',
      guest_name: 'Rahul & Family',
      message: 'Such a lovely page. Sending warm blessings for a joyful and prosperous married life.',
      created_at: new Date().toISOString(),
      status: 'approved',
    },
  ],
};

export function createBlankEvent(ownerId = null) {
  return {
    ...structuredClone(defaultEvent),
    id: crypto.randomUUID(),
    owner_id: ownerId,
    slug: `event-${crypto.randomUUID().slice(0, 8)}`,
    title: 'New Event',
    hosts_display_name: 'Host Names',
    headline: 'Celebrate live with friends and family',
    description: 'Create a polished event page with livestreams, media, and guest wishes.',
    venue_name: 'Venue Name',
    venue_address: 'Venue address',
    status: 'draft',
    media_assets: [],
    video_embeds: [],
    guestbook_entries: [],
  };
}
